// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

interface AwsConfig {
  aws_project_region: string;
}

const awsconfig: AwsConfig = {
  // Add your AWS Amplify configuration here after running `amplify init`
  // This is a placeholder configuration
  aws_project_region: 'eu-west-1',
};

export default awsconfig;
